[project]
name = "hubitat"
version = "0.6.8"
description = "A Hubitat integration for Home Assistant"
authors = [
    {name = "Jason Cheatham", email = "jason@jasoncheatham.com"},
]
dependencies = []
requires-python = ">=3.8,<4.0"
license = {text = "MIT"}

[project.urls]
homepage = ""

[project.optional-dependencies]
[tool.pdm.scripts]
init = {shell = "pdm install && pre-commit install"}
test = {shell = "pyright custom_components/hubitat && pytest tests"}

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.pdm]
includes = []

[tool.pdm.dev-dependencies]
dev = [
    "black>=21.12b0",
    "flake8>=3.8.1",
    "isort>=4.3.21",
    "pre-commit<3.0.0,>=2.4.0",
    "flake8-pyi>=20.5.0",
    "hubitatmaker@file:///${PROJECT_ROOT}/../hubitatmaker.git",
    "homeassistant==2021.12.0",
    "pytest-asyncio>=0.16.0",
]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool.pyright]
include = ["custom_components/hubitat"]
exclude = ["**/__pycache__"]
extraPaths = ["__pypackages__/3.8/lib"]
stubPath = "."
reportDuplicateImport = true
reportMissingImports = true
reportOptionalCall = true
reportOptionalMemberAccess = true
reportOptionalSubscript = true
reportUnusedClass = true
reportUnusedFunction = true
reportUnusedImport = true
reportUnusedVariable = true

[tool.isort]
# https://github.com/timothycrosley/isort
# https://github.com/timothycrosley/isort/wiki/isort-Settings
# splits long import on multiple lines indented by 4 spaces
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
indent = "    "
# by default isort don't check module indexes
not_skip = "__init__.py"
# will group `import x` and `from x import` of the same module.
force_sort_within_sections = true
sections = "FUTURE,STDLIB,INBETWEENS,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
default_section = "THIRDPARTY"
known_first_party = "homeassistant,tests"
forced_separate = "tests"
combine_as_imports = true
